ACTION_RUN    = 1<<0
ACTION_STOP   = 1<<1
ACTION_STATUS = 1<<2
ACTION_ALL    = ACTION_RUN | ACTION_STOP | ACTION_STATUS
COMP_ADMIN    = 1<<3
HOST_ADMIN    = 1<<4
PRIV_ADMIN    = 1<<5
START_SERVER  = 1<<6

def dict():
	return {
		'ACTION_RUN':    ACTION_RUN,
		'ACTION_STOP':   ACTION_STOP,
		'ACTION_STATUS': ACTION_STATUS,
		'COMP_ADMIN':    COMP_ADMIN,
		'HOST_ADMIN':    HOST_ADMIN,
		'PRIV_ADMIN':    PRIV_ADMIN,
		'START_SERVER':  START_SERVER
	}

