ACTION_RUN    = 0#1<<0
ACTION_STOP   = 0#1<<1
ACTION_STATUS = 0#1<<2
ACTION_ALL    = 0#ACTION_RUN | ACTION_STOP | ACTION_STATUS
COMP_ADMIN    = 0#1<<3
HOST_ADMIN    = 0#1<<4
START_SERVER  = 0#<<5


    
